### GET request to create patient
POST http://lb-5b6a3a96.elb.localhost.localstack.cloud:4004/patients
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "john wick",
  "email": "kafka_test@gmail.com",
  "address": "123 main street",
  "dateOfBirth": "1995-09-09",
  "registeredDate": "2024-11-28"
}
###